# Generated by Django 3.2.3 on 2022-06-13 08:23

from django.db import migrations, models
import myapp.functions.fileValidation


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=255)),
                ('vdescriptions', models.TextField()),
                ('vtype', models.CharField(max_length=50)),
                ('vaddress', models.CharField(max_length=255)),
                ('vcharges', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='uploads/', validators=[myapp.functions.fileValidation.validate_file_extension])),
            ],
        ),
    ]
