# Generated by Django 3.2.8 on 2022-06-14 08:42

from django.db import migrations, models
import myapp.functions.fileValidation


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[myapp.functions.fileValidation.validate_file_extension], verbose_name='Venue Image'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vaddress',
            field=models.CharField(max_length=255, verbose_name='Venue Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vcharges',
            field=models.CharField(max_length=15, verbose_name='Venue Charges'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vdescriptions',
            field=models.TextField(verbose_name='Venue Descripton'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vname',
            field=models.CharField(max_length=255, verbose_name='Venue Name'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vtype',
            field=models.CharField(max_length=50, verbose_name='Venue Type'),
        ),
    ]
