# Generated by Django 3.2.8 on 2022-06-14 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220614_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Event Descriptions')),
                ('bookdate', models.DateTimeField(auto_now_add=True, verbose_name='Book Date')),
                ('eventdate', models.DateField(verbose_name='Event Date')),
                ('charges', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_by', to=settings.AUTH_USER_MODEL, verbose_name='Book By')),
            ],
        ),
    ]
